# Generated by Django 6.0.1 on 2026-08-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
